# Generated by Django 6.1.1 on 2026-09-17 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xettuyen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ketqualocao',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='mauimportgiaybao',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='thisinhdata',
            options={'managed': True},
        ),
    ]
