# Generated by Django 6.1.1 on 2026-09-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xettuyen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToHopMon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stt', models.IntegerField()),
                ('ma_to_hop_mon', models.CharField(max_length=10)),
                ('ten_to_hop_mon', models.CharField(max_length=255)),
                ('ma_mon_thi', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'thm',
            },
        ),
    ]
